#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# install packages listed in 'packages' file
sudo apt-get update
sudo apt-get install $(grep -vE "^\s*#" packages  | tr "\n" " ")

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
